using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EndlessEscapade.Generators.Hooks;

[Generator(LanguageNames.CSharp)]
public sealed class GlobalProjectileHooksGenerator : IIncrementalGenerator
{
    private const string ToolVersion = "0.1";

    private const string GlobalProjectileTypeName = "Terraria.ModLoader.GlobalProjectile";
    private const string ProjectileTypeName = "Terraria.Projectile";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var provider = initializationContext.CompilationProvider.Select(
            static (compilation, _) => (
                GlobalProjectileSymbol: compilation.GetTypeByMetadataName(GlobalProjectileTypeName),
                ProjectileSymbol: compilation.GetTypeByMetadataName(ProjectileTypeName)
            )
        );

        initializationContext.RegisterSourceOutput(
            provider,
            static (sourceContext, symbols) => {
                sourceContext.AddSource(
                    "GlobalProjectileHooks.g.cs",
                    GenerateGlobalProjectileHooks(symbols.GlobalProjectileSymbol, symbols.ProjectileSymbol)
                );
            }
        );
    }

    private static string GenerateGlobalProjectileHooks(INamedTypeSymbol globalProjectileSymbol, INamedTypeSymbol projectileSymbol) {
        var builder = new StringBuilder(
            $@"// <auto-generated/>

using System;
using System.Reflection;
using Terraria;
using Terraria.ModLoader;
using MonoMod.RuntimeDetour;
using EndlessEscapade.Utilities;

namespace EndlessEscapade.Core.EC;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.GlobalProjectileHooksGenerator"", ""{ToolVersion}"")]
public sealed class GlobalProjectileHooks : ModSystem
{{
    public override void Load() {{
        base.Load();

"
        );

        var methods = globalProjectileSymbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static symbol => symbol.IsVirtual && !symbol.IsStatic);

        foreach (var method in methods) {
            AppendCallForMethod(builder, method);
        }

        builder.AppendLine("    }\n");

        foreach (var method in methods) {
            AppendHookForMethod(builder, method, projectileSymbol);
        }

        builder.Append("}");

        return builder.ToString();
    }

    private static void AppendCallForMethod(StringBuilder builder, IMethodSymbol methodSymbol) {
        var methodName = methodSymbol.Name;
        var hookName = $"{methodName}_Hook";

        builder.AppendLine($@"        MonoModHooks.Add(typeof(GlobalProjectile).GetMethod(""{methodName}""), {hookName});");
    }

    private static void AppendHookForMethod(StringBuilder builder, IMethodSymbol methodSymbol, INamedTypeSymbol projectileSymbol) {
        var parameters = methodSymbol.Parameters;

        var parameterNames = string.Join(", ", parameters.Select(static symbol =>
            symbol.RefKind switch {
                RefKind.Ref => $"ref {symbol.Type} {symbol.Name}",
                RefKind.In => $"in {symbol.Type} {symbol.Name}",
                RefKind.Out => $"out {symbol.Type} {symbol.Name}",
                _ => $"{symbol.Type} {symbol.Name}"
            }
        ));

        var argumentNames = string.Join(", ", parameters.Select(static symbol =>
            symbol.RefKind switch {
                RefKind.Ref => $"ref {symbol.Name}",
                RefKind.In => $"in {symbol.Name}",
                RefKind.Out => $"out {symbol.Name}",
                _ => symbol.Name
            }
        ));

        var methodName = methodSymbol.Name;

        var originType = !methodSymbol.ReturnsVoid
            ? $"Func<GlobalProjectile, {string.Join(", ", parameters.Select(static symbol => symbol.Type.ToString()))}, {methodSymbol.ReturnType}>"
            : $"Action<{string.Join(", ", new[] { "GlobalProjectile" }.Concat(parameters.Select(static symbol => symbol.Type.ToString())))}>";

        var delegateName = $"{methodName}Callback";
        var delegateType = $"    private delegate {methodSymbol.ReturnType.ToString()} {delegateName}(GlobalProjectile self, {parameterNames});";

        var returnType = methodSymbol.ReturnType.ToString();

        var body = !methodSymbol.ReturnsVoid
            ? $"return orig(self, {argumentNames});"
            : $"orig(self, {argumentNames});";

        var hasProjectileParameter = parameters.Any(symbol => SymbolEqualityComparer.Default.Equals(symbol.Type, projectileSymbol));

        var condition = hasProjectileParameter
            ? $"component.Enabled && ProjectileComponentSystem.HasDependencies(component.GetType(), projectile)"
            : "component.Enabled";

        var hookName = $"{methodName}_Hook";

        builder.AppendLine($@"{delegateType}

    private static {returnType} {hookName}({delegateName} orig, GlobalProjectile self, {parameterNames}) {{
        if (self is not ProjectileComponent component || ({condition})) {{
            {body}
        }}");

        if (!methodSymbol.ReturnsVoid) {
            builder.AppendLine(@"
        return default;");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
