using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EndlessEscapade.Generators.Hooks;

[Generator(LanguageNames.CSharp)]
public sealed class GlobalProjectileHooksGenerator : IIncrementalGenerator
{
    private const string ToolVersion = "0.1";

    private const string GlobalProjectileTypeName = "Terraria.ModLoader.GlobalProjectile";
    private const string ProjectileTypeName = "Terraria.Projectile";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var provider = initializationContext.CompilationProvider.Select(static (compilation, _) => (
            GlobalProjectileSymbol: compilation.GetTypeByMetadataName(GlobalProjectileTypeName),
            ProjectileSymbol: compilation.GetTypeByMetadataName(ProjectileTypeName)
        ));

        initializationContext.RegisterSourceOutput(
            provider,
            static (sourceContext, symbols) => {
                sourceContext.AddSource("GlobalProjectileHooks.g.cs", GenerateGlobalProjectileHooks(symbols.GlobalProjectileSymbol, symbols.ProjectileSymbol));
            }
        );
    }

    private static string GenerateGlobalProjectileHooks(INamedTypeSymbol globalProjectileSymbol, INamedTypeSymbol projectileSymbol) {
        var builder = new StringBuilder($@"// <auto-generated/>

using System;
using System.Reflection;
using Terraria;
using Terraria.ModLoader;
using MonoMod.RuntimeDetour;
using EndlessEscapade.Utilities;

namespace EndlessEscapade.Core.EC;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.GlobalProjectileHooksGenerator"", ""{ToolVersion}"")]
public sealed class GlobalProjectileHooks : ModSystem
{{
    public override void Load() {{
        base.Load();
");

        var methods = globalProjectileSymbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static symbol => symbol.IsVirtual && !symbol.IsStatic);

        foreach (var method in methods) {
            AppendHookForMethod(builder, method, projectileSymbol);
        }

        builder.AppendLine("    }\n}");

        return builder.ToString();
    }

    private static void AppendHookForMethod(StringBuilder builder, IMethodSymbol methodSymbol, INamedTypeSymbol projectileSymbol) {
        var methodName = methodSymbol.Name;
        var parameters = methodSymbol.Parameters;
        var parameterList = string.Join(", ", parameters.Select(static symbol => $"{symbol.Type} {symbol.Name}"));
        var invokeArguments = string.Join(", ", parameters.Select(static symbol => symbol.Name));

        var delegateType = $"Action<{string.Join(", ", new[] { "GlobalProjectile" }.Concat(parameters.Select(p => p.Type.ToString())))}>";

        var hasProjectileParameter = parameters.Any(symbol => SymbolEqualityComparer.Default.Equals(symbol.Type, projectileSymbol));

        if (hasProjectileParameter) {
            builder.AppendLine($@"
        MonoModHooks.Add(
            typeof(GlobalProjectile).GetMethod(""{methodName}""),
            ({delegateType} orig, GlobalProjectile self, {parameterList}) => {{
                if (self is not ProjectileComponent component || (component.Enabled && ProjectileComponentSystem.HasDependencies(component.GetType(), projectile))) {{
                    orig(self, {invokeArguments});
                }}
            }}
        );");
        }
        else {
            builder.AppendLine($@"
        MonoModHooks.Add(
            typeof(GlobalProjectile).GetMethod(""{methodName}"", Flags),
            ({delegateType} orig, GlobalProjectile self, {parameterList}) => {{
                if (self is not ProjectileComponent component || component.Enabled) {{
                    orig(self, {invokeArguments});
                }}
            }}
        );");
        }
    }
}