using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EndlessEscapade.Generators.Hooks;

[Generator(LanguageNames.CSharp)]
public sealed class ProjectileComponentGenerator : IIncrementalGenerator
{
    private const string ToolVersion = "0.1";

    private const string GlobalProjectileTypeName = "Terraria.ModLoader.GlobalProjectile";
    private const string ProjectileTypeName = "Terraria.Projectile";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var provider = initializationContext.CompilationProvider.Select(
            static (compilation, _) => {
                var globalProjectileSymbol = compilation.GetTypeByMetadataName(GlobalProjectileTypeName);

                var globalProjectileHooks = globalProjectileSymbol
                    .GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(static symbol =>
                        symbol.IsVirtual &&
                        !symbol.IsStatic &&
                        !symbol.GetAttributes().Any(attribute => attribute.AttributeClass.GetType() != typeof(ObsoleteAttribute))
                    );

                return (
                    GlobalProjectileHooks: globalProjectileHooks,
                    ProjectileSymbol: compilation.GetTypeByMetadataName(ProjectileTypeName)
                );
            }
        );

        initializationContext.RegisterSourceOutput(
            provider,
            static (sourceContext, symbols) => {
                sourceContext.AddSource(
                    "ProjectileComponent.Hooks.g.cs",
                    SourceText.From(GenerateGlobalProjectileHooks(symbols.GlobalProjectileHooks, symbols.ProjectileSymbol), Encoding.UTF8)
                );
            }
        );
    }

    private static string GenerateGlobalProjectileHooks(IEnumerable<IMethodSymbol> globalProjectileHooks, INamedTypeSymbol projectileSymbol) {
        var builder = new StringBuilder(
            $@"// <auto-generated/>

using EndlessEscapade.Utilities;

namespace EndlessEscapade.Core.EC;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.ProjectileComponentGenerator"", ""{ToolVersion}"")]
public abstract partial class ProjectileComponent : GlobalProjectile
{{
    public virtual void SafeSetDefaults(Projectile entity) {{
        base.SetDefaults(entity);
    }}

    public sealed override void SetDefaults(Projectile entity) {{
        if (Enabled && ProjectileComponentLoader.HasRequirements(entity, this)) {{
            SafeSetDefaults(entity);
        }}
    }}
"
        );

        foreach (var method in globalProjectileHooks) {
            AppendHookForMethod(builder, method, projectileSymbol);
        }

        builder.Append("}");

        return builder.ToString();
    }

    private static void AppendHookForMethod(StringBuilder builder, IMethodSymbol methodSymbol, INamedTypeSymbol projectileSymbol) {
        var parameters = methodSymbol.Parameters;

        var parameterNames = string.Join(", ", parameters.Select(static symbol =>
            symbol.RefKind switch {
                RefKind.Ref => $"ref {symbol.Type} {symbol.Name}",
                RefKind.In => $"in {symbol.Type} {symbol.Name}",
                RefKind.Out => $"out {symbol.Type} {symbol.Name}",
                _ => $"{symbol.Type} {symbol.Name}"
            }
        ));

        var argumentNames = string.Join(", ", parameters.Select(static symbol =>
            symbol.RefKind switch {
                RefKind.Ref => $"ref {symbol.Name}",
                RefKind.In => $"in {symbol.Name}",
                RefKind.Out => $"out {symbol.Name}",
                _ => symbol.Name
            }
        ));

        var methodName = methodSymbol.Name;

        var originType = !methodSymbol.ReturnsVoid
            ? $"Func<GlobalProjectile, {string.Join(", ", parameters.Select(static symbol => symbol.Type.ToString()))}, {methodSymbol.ReturnType}>"
            : $"Action<{string.Join(", ", new[] { "GlobalProjectile" }.Concat(parameters.Select(static symbol => symbol.Type.ToString())))}>";

        var returnType = methodSymbol.ReturnType.ToString();

        var conditionBody = !methodSymbol.ReturnsVoid
            ? $"return Safe{methodName}({argumentNames});"
            : $"Safe{methodName}({argumentNames});";

        var defaultBody = !methodSymbol.ReturnsVoid
            ? $"return base.{methodName}({argumentNames});"
            : $"base.{methodName}({argumentNames});";

        var hasProjectileParameter = parameters.Any(symbol => SymbolEqualityComparer.Default.Equals(symbol.Type, projectileSymbol));

        var condition = hasProjectileParameter
            ? $"Enabled && ProjectileComponentLoader.HasRequirements(projectile, this)"
            : "Enabled";

        builder.AppendLine();
        builder.AppendLine($@"    public virtual {returnType} Safe{methodName}({parameterNames}) {{
        {defaultBody}
    }}

    public sealed override {returnType} {methodName}({parameterNames}) {{
        if ({condition}) {{
            {conditionBody}
        }}");

        if (!methodSymbol.ReturnsVoid) {
            builder.AppendLine($@"
        return base.{methodName}({argumentNames});");
        }

        builder.AppendLine("    }");
    }
}
