<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../build/Mod.Build.targets" />
    
    <PropertyGroup>
        <NoModPackaging>true</NoModPackaging>
    </PropertyGroup>
    
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    </ItemGroup>

</Project>
