<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../build/Mod.Build.targets" />
    
    <PropertyGroup>
        <NoModPackaging>true</NoModPackaging>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Core\_ECS\" />
    </ItemGroup>

</Project>
