<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../build/Mod.Build.targets"/>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EndlessEscapade.Generators\EndlessEscapade.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
    
    <ItemGroup>
        <Reference Include="StructureHelper">
            <HintPath>lib\StructureHelper.dll</HintPath>
        </Reference>
    </ItemGroup>

    <!-- Required for source generators to properly recognize assets. -->
    
    <ItemGroup>
        <AdditionalFiles Include="Assets/**/*.png" />
        <AdditionalFiles Include="Assets/**/*.fxc" />
        <AdditionalFiles Include="Assets/**/*.wav" />
        <AdditionalFiles Include="Assets/**/*.ogg" />
        <AdditionalFiles Include="Assets/**/*.mp3" />
    </ItemGroup>

</Project>

