using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using EndlessEscapade.Generators.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Primitives;

namespace EndlessEscapade.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AssetGenerator : IIncrementalGenerator
{
    private const string TOOL_VERSION = "1.0";

    private const string IMAGE_EXTENSION = ".png";
    private const string EFFECT_EXTENSION = ".xnb";
    private const string WAV_EXTENSION = ".wav";
    private const string OGG_EXTENSION = ".ogg";

    private static readonly string[] SupportedExtensions = new[] { IMAGE_EXTENSION, EFFECT_EXTENSION, WAV_EXTENSION, OGG_EXTENSION };

    private enum AssetType
    {
        Texture2D,
        Effect,
        SoundEffect,
    }
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assetRootFolder = context.AdditionalTextsProvider.Where(file => file.Path.EndsWith("EEAssetRoot.txt"))
        .Collect()
        .Select(static (files, _) =>
        {
            var directory = Path.GetDirectoryName(files.FirstOrDefault()?.Path)?.Replace('\\', '/');
            if (string.IsNullOrWhiteSpace(directory))
                return null;
            return directory;
        });

        var files = context.AdditionalTextsProvider
        .Where(static file =>
        {
            foreach (var extension in SupportedExtensions)
                if (file.Path.EndsWith(extension, StringComparison.OrdinalIgnoreCase))
                    return true;
            return false;
        }).Select((file, _) => file.Path.Replace('\\', '/'));

        // Files are grouped together by directory.
        // - One generated file per asset is the most efficient for cache but it generates too many files.
        // - One generated file with all assets can generate a reaaally big file which the compiler
        // may not like and is also bad for cache, because changing one file will have to rebuild
        // the entire generated file.
        // - Grouping by directory will trigger regenerating a file only for the directory it belongs to.
        var contents = files
        .Combine(assetRootFolder)
        .Where(tuple => tuple.Right != null && tuple.Left.StartsWith(tuple.Right))
        .Select(static (tuple, _) =>
        {
            var rootFolder = tuple.Right;
            var file = tuple.Left;
            var fullPath = file.AsSegment(rootFolder.Length + 1);

            var path = PathUtils.RemoveExtension(fullPath);
            var folder = PathUtils.GetFolder(fullPath);
            var name = PathUtils.GetFileNameWithoutExtension(fullPath);
            var extension = PathUtils.GetExtension(fullPath);

            if (folder.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
                folder = folder.Substring("Assets/".Length);

            var assetType = AssetType.SoundEffect;
            if (extension.EndsWith(IMAGE_EXTENSION, StringComparison.OrdinalIgnoreCase))
                assetType = AssetType.Texture2D;
            else if (extension.EndsWith(EFFECT_EXTENSION, StringComparison.OrdinalIgnoreCase))
                assetType = AssetType.Effect;

            return new AssetFile(
                Path: path,
                Folder: folder,
                Name: name,
                Extension: extension,
                AssetType: assetType
            );
        })
        .Collect()
        .SelectMany((files, _) => files.GroupBy(f => f.Folder, f => f, (key, group) => (key, group.ToImmutableArray())).ToImmutableArray());

        // outputs 
        context.RegisterSourceOutput(assetRootFolder, (context, path) =>
        {
            string warn = "";
            if (path == null)
                warn = "#warning missing EEAssetRoot.txt file";
            context.AddSource("Assets.default.g.cs", $@"// <auto-generated/>
namespace EndlessEscapade;
[System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(AssetGenerator).FullName}"", ""{TOOL_VERSION}"")]
partial class Assets {{ }}
{warn}
");
        });
        context.RegisterSourceOutput(contents, static (sourceContext, tuple) =>
        {
            var (folder, files) = tuple;
            sourceContext.CancellationToken.ThrowIfCancellationRequested();
            using var writer = new IndentedStringWriter(1024);
            writer.WriteLine($@"// <auto-generated/>
using ReLogic.Content;
using Terraria.Audio;

using ImageAsset = EndlessEscapade.AssetWrapper<Microsoft.Xna.Framework.Graphics.Texture2D>;
using EffectAsset = EndlessEscapade.AssetWrapper<Microsoft.Xna.Framework.Graphics.Effect>;
using SoundAsset = Terraria.Audio.SoundStyle;

namespace EndlessEscapade;

partial class Assets
{{");
            writer.Indent++;
            foreach (var part in folder.SplitEx('/', StringSplitOptions.RemoveEmptyEntries))
            {
                writer.WriteLine($"public partial class {part}");
                writer.WriteLine("{");
                writer.Indent++;
            }

            foreach (var file in files)
            {
                switch (file.AssetType)
                {
                    case AssetType.Texture2D:
                        writer.WriteLine($"public static ImageAsset {file.Name} {{ get; }} = new(\"{file.Path}\");");
                        break;
                    case AssetType.Effect:
                        writer.WriteLine($"public static EffectAsset {file.Name} {{ get; }} = new(\"{file.Path}\");");
                        break;
                    case AssetType.SoundEffect:
                        writer.WriteLine($"public static SoundAsset {file.Name} {{ get; }} = new(\"{file.Path}\");");
                        break;
                }
            }

            foreach (var part in folder.SplitEx('/', StringSplitOptions.RemoveEmptyEntries))
            {
                writer.Indent--;
                writer.WriteLine("}");
            }

            writer.Indent--;
            writer.WriteLine("}"); // Assets class

            var sourceText = writer.ToStringAndClear();

            writer.Write($"Assets.{folder}.cs");
            writer.Builder.Replace('/', '.');
            var fileName = writer.ToString();
            if (fileName.Equals("Assets..cs", StringComparison.Ordinal)) // file was on root
                fileName = "Assets.g.cs";

            sourceContext.AddSource(fileName, sourceText);
        });
    }
    private static class PathUtils
    {
        public static StringSegment GetFolder(StringSegment path)
        {
            var result = path;
            var lastSlash = result.LastIndexOf('/');
            if (lastSlash == -1)
                return default;
            return result.Substring(0, lastSlash);
        }
        public static StringSegment GetFileNameWithoutExtension(StringSegment file)
        {
            var result = file;
            var lastDot = result.LastIndexOf('.');
            if (lastDot != -1)
                result = result.Substring(0, lastDot);
            var lastSlash = result.LastIndexOf('/');
            if (lastSlash != -1)
                result = result.Substring(lastSlash + 1);
            return result;
        }
        /// <summary>
        /// Returns the extension including the dot '.' of the given file path.
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public static StringSegment GetExtension(StringSegment file)
        {
            var index = file.LastIndexOf('.');
            if (index == -1)
                return default;
            return file.Substring(index);
        }
        public static StringSegment RemoveExtension(StringSegment file)
        {
            var index = file.AsSpan().LastIndexOf('.');
            if (index == -1)
                return file;
            return file.Substring(0, index);
        }
    }

    /// <summary>
    /// Represents an asset file.
    /// </summary>
    /// <param name="Path">The path (relative to EE source) of the asset without file extension.</param>
    /// <param name="Folder">The path (relative to EE source) of the directory the asset is in.<br/>Does not end with '/'.</param>
    /// <param name="Name">The name of the file, without extension.</param>
    /// <param name="Extension">The extension of the file.</param>
    private readonly record struct AssetFile(StringSegment Path, StringSegment Folder, StringSegment Name, StringSegment Extension, AssetType AssetType)
    {
        public bool Equals(AssetFile other)
            => Path.Equals(other.Path, StringComparison.OrdinalIgnoreCase) && Extension.Equals(other.Extension, StringComparison.OrdinalIgnoreCase);

        public override int GetHashCode() => HashCode.Combine(Path, Extension);
    };
}