using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using EndlessEscapade.Generators.Utilities;
using Microsoft.CodeAnalysis;

namespace EndlessEscapade.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AssetGenerator : IIncrementalGenerator
{
    private const string TOOL_VERSION = "1.0";

    private const string IMAGE_EXTENSION = ".png";
    private const string EFFECT_EXTENSION = ".xnb";
    private const string WAV_EXTENSION = ".wav";
    private const string OGG_EXTENSION = ".ogg";

    private const string ASSET_PATH_PREFIX = "/ModSources/endless-escapade/src/EndlessEscapade/Assets";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var supportedExtensions = new[] { IMAGE_EXTENSION, EFFECT_EXTENSION, WAV_EXTENSION, OGG_EXTENSION };
        var directoryBlackList = new[] { "Textures/Gores" };

        var files = context.AdditionalTextsProvider
            .Where(file =>
        {
            var fullPath = file.Path.Replace('\\', '/');
            
            var hasSupportedExtension = supportedExtensions.Any(ext => fullPath.EndsWith(ext, StringComparison.OrdinalIgnoreCase));
            var isNotBlacklisted = !directoryBlackList.Any(dir => fullPath.IndexOf(dir, StringComparison.OrdinalIgnoreCase) >= 0);

            return hasSupportedExtension && isNotBlacklisted;
        });
        

        var contents = files
            .Select(
            static (file, _) =>
            {
                var fullPath = file.Path.Replace('\\', '/');
                var index = fullPath.IndexOf(ASSET_PATH_PREFIX, StringComparison.Ordinal);

                var name = Path.GetFileNameWithoutExtension(fullPath);
                var path = Path.ChangeExtension(index == -1 ? fullPath : fullPath.Substring(index + ASSET_PATH_PREFIX.Length), null);
                var extension = Path.GetExtension(fullPath);

                return new AssetFile(
                    Name: name,
                    Path: path,
                    Extension: extension
                    );
            }
        );

        context.RegisterSourceOutput(contents.Collect(), static (sourceContext, collectedFiles) => { sourceContext.AddSource("Assets.g.cs", GenerateContainers(collectedFiles)); });
    }

    private static string GenerateContainers(IEnumerable<AssetFile> files)
    {
        var assetFiles = files.ToList();
        
        var images = assetFiles.Where(f => f.Extension == IMAGE_EXTENSION)
                          .Select(f => GenerateImage(f.Name, f.Path));

        var effects = assetFiles.Where(f => f.Extension == EFFECT_EXTENSION)
                           .Select(f => GenerateEffect(f.Name, f.Path));

        var audioWav = assetFiles.Where(f => f.Extension == WAV_EXTENSION)
                            .Select(f => GenerateSound(f.Name, f.Path));

        var audioOgg = assetFiles.Where(f => f.Extension == OGG_EXTENSION)
                            .Select(f => GenerateSound(f.Name, f.Path));

        var usings = new HashSet<string>()
        {
            "using ReLogic.Content;",
            "using Terraria.Audio"
        };

        return $@"// <auto-generated />

{string.Join("\n", usings)};

[System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(AssetGenerator).FullName}"", ""{TOOL_VERSION}"")]
public static class Assets
{{
    public static class Images
    {{
{string.Join("\n", images)}
    }}

    public static class Effects
    {{
{string.Join("\n", effects)}
    }}

    public static class Sounds
    {{
{string.Join("\n", audioOgg)}
{string.Join("\n", audioWav)}
    }}
}}
";
    }

    private static string GenerateImage(string name, string path)
    {
        return $@"        public static readonly Asset<Texture2D> {name} = ModContent.Request<Texture2D>(""{path}"");";
    }

    private static string GenerateEffect(string name, string path)
    {
        return $@"        public static readonly Asset<Effect> {name} = ModContent.Request<Effect>(""{path}"");";
    }

    private static string GenerateSound(string name, string path)
    {
        return $@"        public static readonly SoundStyle {name} = new(""{path}"");";
    }

    private record struct AssetFile(string Name, string Path, string Extension);
}