using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace EndlessEscapade.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ImageGenerator : IIncrementalGenerator
{
    private const string TOOL_VERSION = "1.0";
    
    private const string IMAGE_EXTENSION = ".png";
    
    private const string IMAGE_PATH_PREFIX = "/ModSources/endless-escapade/src/";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider.Where(static file => file.Path.EndsWith(IMAGE_EXTENSION));
        
        var contents = files.Select
        (
            static (file, _) =>
            {
                var fullPath = file.Path.Replace('\\', '/');
    
                var index = fullPath.IndexOf(IMAGE_PATH_PREFIX);
                
                var name = Path.GetFileNameWithoutExtension(fullPath);
                var path = Path.ChangeExtension(index == -1 ? fullPath : fullPath.Substring(index + IMAGE_PATH_PREFIX.Length), null);
                
                return 
                (
                    Name: name,
                    Path: path
                );
            }
        );

        context.RegisterSourceOutput(contents.Collect(), static (sourceContext, collectedFiles) => sourceContext.AddSource("ImageAssets.g.cs", GenerateContainer(collectedFiles)));
    }

    private static string GenerateContainer(IEnumerable<(string Name, string Path)> files)
    {
        var fields = files.Select(static file => $"    public static readonly Asset<Texture2D> {file.Name} = ModContent.Request<Texture2D>(\"{file.Path}\");");

        return $@"// <auto-generated />

using ReLogic.Content;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(ImageGenerator).FullName}"", ""{TOOL_VERSION}"")]
public static class ImageAssets
{{
{string.Join("\n\n", fields)}
}}
";
    }

    private static string GenerateImage(string name, string path)
    {
        return $@"    public static readonly Asset<Texture2D> {name} = ModContent.Request<Texture2D>(""{path}"");";
    }
}