using System.IO;
using System.Text;
using EndlessEscapade.Generators.Utilities;
using Hjson;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Newtonsoft.Json;

namespace EndlessEscapade.Generators.Data;

[Generator(LanguageNames.CSharp)]
public sealed class ChestLootGenerator : IIncrementalGenerator
{
    private const string TOOL_VERSION = "0.1";

    /// <summary>
    ///     The file extension associated with this generator.
    /// </summary>
    public const string EXTENSION = ".eeloot";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var files = initializationContext.AdditionalTextsProvider.Where(static file => file.Path.EndsWith(EXTENSION));

        var contents = files.Select(
            static (text, token) => {
                var content = text.GetText(token);

                var json = HjsonValue.Parse(content.ToString()).ToString(Stringify.Plain);
                var data = JsonConvert.DeserializeObject<ChestLootData>(json);

                return (
                    Name: Path.GetFileNameWithoutExtension(text.Path),
                    Data: data
                );
            }
        );

        initializationContext.RegisterSourceOutput(
            contents,
            static (sourceContext, content) => {
                sourceContext.AddSource(
                    $"{content.Name}.g.cs",
                    SourceText.From(GenerateChestLoot(content.Name, in content.Data), Encoding.UTF8)
                );
            }
        );
    }

    private static string GenerateChestLoot(string name, in ChestLootData data) {
        return $@"// <auto-generated/>

namespace EndlessEscapade.Common.World;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.ChestLootGenerator"", ""{TOOL_VERSION}"")]
public sealed class {name} : ModChestLoot
{{
    protected override string TilePath {{ get; }} = ""{data.TilePath}"";

    protected override string ItemPath {{ get; }} = ""{data.ItemPath}"";

    public override int[] Frames {{ get; }} = {data.Frames.ToStringArray()};

    public override StackData Stack {{ get; }} = new({data.MinStack}, {data.MaxStack});

    public override int Chance {{ get; }} = {data.Chance};

    public override bool RandomSlot {{ get; }} = {data.RandomSlot.ToString().ToLower()};
}}";
    }
}
