using System.IO;
using System.Text;
using EndlessEscapade.Generators.Utilities;
using Hjson;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Newtonsoft.Json;

namespace EndlessEscapade.Generators.Data;

[Generator(LanguageNames.CSharp)]
public sealed class AmbienceSoundGenerator : IIncrementalGenerator
{
    private const string TOOL_VERSION = "0.1";

    /// <summary>
    ///     The file extension associated with this generator.
    /// </summary>
    public const string EXTENSION = ".eesound";

    public void Initialize(IncrementalGeneratorInitializationContext initializationContext) {
        var files = initializationContext.AdditionalTextsProvider.Where(static file => file.Path.EndsWith(EXTENSION));

        var contents = files.Select(
            static (text, token) => {
                var content = text.GetText(token);

                var json = HjsonValue.Parse(content.ToString()).ToString(Stringify.Plain);
                var data = JsonConvert.DeserializeObject<AmbienceSoundData>(json);

                return (
                    Name: Path.GetFileNameWithoutExtension(text.Path),
                    Data: data
                );
            }
        );

        initializationContext.RegisterSourceOutput(
            contents,
            static (sourceContext, content) => {
                sourceContext.AddSource(
                    $"{content.Name}.g.cs",
                    SourceText.From(GenerateAmbienceSound(content.Name, in content.Data), Encoding.UTF8)
                );
            }
        );
    }

    private static string GenerateAmbienceSound(string name, in AmbienceSoundData data) {
        return $@"// <auto-generated/>

using Terraria.Audio;
using ReLogic.Utilities;

namespace EndlessEscapade.Common.Ambience;

[System.CodeDom.Compiler.GeneratedCodeAttribute(""EndlessEscapade.Generators.AmbienceSoundGenerator"", ""{TOOL_VERSION}"")]
public sealed class {name} : ModAmbienceSound
{{
	public override SoundStyle Sound {{ get; }} = new(""{data.SoundStyleData.SoundPath}"", {data.SoundStyleData.Variants}, SoundType.Ambient) {{
		Volume = {data.SoundStyleData.Volume}f
	}};

    public override int Chance {{ get; }} = {data.Chance};

    public override bool IsAmbienceActive(in AmbienceContext context) {{
        return SignalsSystem.GetSignal({data.Signals.ToStringArray()});
    }}
}}";
    }
}
