name: Build

env:
  TML_BUILD_PATH_OVERRIDE: ./bin

on:
  push:
    branches: [stable]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and install tModLoader
        run: |
          curl -s -L https://github.com/tModLoader/tModLoader/releases/latest/download/tModLoader.zip -o tModLoader.zip
          unzip -q -o tModLoader.zip -d ../tModLoader
          rm tModLoader.zip

      - name: Create tModLoader.targets file
        shell: bash
        run: |
          cat >> ../tModLoader.targets << EOF
          <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
            <Import Project="tModLoader\tMLMod.targets" />
          </Project>
          EOF

      - name: Build solution
        run: dotnet build EndlessEscapade.sln --configuration Release

  deploy:
    runs-on: windows-latest
      
    steps:
      - name: Deploy EndlessEscapade.tmod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessEscapade.tmod
          path: ./bin/tModLoader/Mods/EndlessEscapade.tmod

      - name: Deploy EndlessEscapade.dll Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessEscapade.dll
          path: .src/EndlessEscapade/bin/Release/net8.0/EndlessEscapade.dll

      - name: Deploy EndlessEscapade.Generators.dll Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessEscapade.Generators.dll
          path: .src/EndlessEscapade.Generators/bin/Release/netstandard2.0/EndlessEscapade.Generators.dll

      - name: Deploy EndlessEscapade.Tests.dll Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessEscapade.dll
          path: .src/EndlessEscapade.Tests/bin/Release/net8.0/EndlessEscapade.Tests.dll

  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create Pre-Release
        uses: actions/create-release@v1
        with:
          files: |
            EndlessEscapade.tmod/EndlessEscapade.tmod
            EndlessEscapade.dll/EndlessEscapade.dll
            EndlessEscapade.Generators.dll/EndlessEscapade.Generators.dll
            EndlessEscapade.Tests.dll/EndlessEscapade.Tests.dll
          tag_name: test-v0.${{ github.run_number }}
          prerelease: true
          name: Endless Escapade test-v0.${{ github.run_number }}
          body: |
            New pre-release of Endless Escapade is ready!

      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.PRIVATE_DISCORD_BUILD_WEBHOOK_TOKEN }}
          title: New Pre-Release Published
          description: |
            A new pre-release version of `Endless Escapade` has been published!
            [View Release](https://github.com/EndlessEscapade/endless-escapade/releases/tag/test-v0.${{ github.run_number }})
          
  publish:
    runs-on: windows-latest

    steps:
      - name: Deploy action across Discord
        uses: sarisia/actions-status-discord@v1  
        with:
          webhook: ${{ secrets.PRIVATE_DISCORD_BUILD_WEBHOOK_TOKEN }}
          title: New version of `Endless Escapade` is ready!
          description: |
            Click [here](https://github.com/EndlessEscapade/endless-escapade/actions/runs/${{ github.run_id }}) to view.
